<form action="<?= $block->getUrl('nbox_shipping/settings/login') ?>" method="post">
    <input type="hidden" name="form_key" value="<?= $block->getFormKey() ?>" />
    <label for="username">Username:</label>
    <input type="text" id="username" name="username" required>

    <label for="password">Password:</label>
    <input type="password" id="password" name="password" required>

    <button type="submit">Login</button>
</form>